name: "Deploy to NuGet"

on: 
  push:
    tags:
      - "v*"

env:
  PROJECT_PATH: "src/AM.Sport.Tracking/AM.Sport.Tracking.csproj"
  PACKAGE_OUTPUT: ${{ github.workspace }}\output
  NUGET_URL: "https://api.nuget.org/v3/index.json"

jobs:
  deploy:
    name: "Deploy"
    runs-on: "ubuntu-latest"
    
    steps:
    
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Install .NET"
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "8.0.x"

    - name: "Restore packages"
      run: dotnet restore ${{ env.PROJECT_PATH }}
    
    - name: "Build projects"
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
    
    - name: "Get version"
      id: version-from-tag
      uses: jannemattila/get-version-from-tag@v3

    - name: "Pack projects"
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.version-from-tag.outputs.version }} --output ${{ env.PACKAGE_OUTPUT }}

    - name: "Push packages"
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_URL }}